{% set name = "skl2onnx" %}
{% set version = "1.14.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/skl2onnx-{{ version }}.tar.gz
  sha256: 54b10a7c62ce2aee4f947bd3a96d7edadef91d5da68de7b33e4ceed3fd07d5dc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy >=1.15
    - onnx >=1.2.1
    - onnxconverter-common >=1.7.0
    - protobuf
    - scikit-learn <1.3,>=0.19
    - scipy >=1.0
    - packaging

test:
  imports:
    - skl2onnx
    - skl2onnx.algebra
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/onnx/sklearn-onnx
  summary: Convert scikit-learn models to ONNX
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - janjagusch
    - cbourjau
    - jtilly
